### PR TITLE
Edit _config.yml file

### PR DESCRIPTION
**Pull request by zylee348**
- Updated command summary
- Edited _config.yml file title and repository to "TABS" and "AY2223S1-CS2103T-W10-1/tp

### CODE REVIEW

**Comment by zylee348** [comment]
does the merge commit button after resolving the conflict cause it to merge the whole pull request?

**Comment by Aloynz** [comment]
I think the website link from the README still does not work after modifying the _config.yml file.

**Comment by zylee348** [comment]
> I think the website link from the README still does not work after modifying the _config.yml file.

might need to merge into master before it begins to work

**Comment by CedricChia123** [comment]
LGTM

**Pull request merged**
